### ISSUE TITLE
Create FyneApp.toml so it can be installed from fyne

### ISSUE THREAD

**Issue by lostdusty** [tomsquest/fynodoro#20]
Adding a `FyneApp.toml` would allow users to install your app using `fyne get`, as shown by this error I got: 
![image](https://github.com/tomsquest/fynodoro/assets/47502554/b20a9912-612e-4092-8ad2-1b8829f56fcd)

[Documentation here](https://docs.fyne.io/started/metadata.html)

**Comment by tomsquest** [comment]
Hi @lostdusty 

I added a basic `FyneApp.toml` in f1859d0a8db1269731c8c6d663aa9629f636ff21

Can you double-check, and close the issue if it is fine for you.

**Comment by lostdusty** [comment]
Looks all good!
![image](https://github.com/tomsquest/fynodoro/assets/47502554/24becfd4-3f9a-4dc3-95b2-106a68a1d223)
